LabelPrintingAPP/LabelPrintingVestey/Controllers/LabelController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using LabelPrintingVestey.Models;
using LabelPrintingVestey.Baseclass;
using System.Data;
using System.Drawing.Printing;
using System.Management;
using System.Drawing;
using System.Windows.Forms;
using System.Linq;
using System;
using Newtonsoft.Json;

namespace LabelPrintingVestey.Controllers
{
    public class LabelController : Controller
    {
        // GET: Label
        public ActionResult Index()
        {
            
            return View();
        }

        //public ActionResult PrintLabel(LabelModel mdl)
        //{

        //    if (ModelState.IsValid) {
        //        DB _db = new DB();
        //        var ds = _db.GetOrderDetails(mdl.SalesOrderNo);
        //        PrintLanscape(ds,mdl);
        //    }
        //        SelectList lst = new SelectList(new List<SelectListItem> {
        //    new SelectListItem { Text ="Printronix Auto ID T8204 - PGL",Value="Printronix Auto ID T8204 - PGL" },
        //     }, "Value", "Text");

        //        ViewBag.Printer = lst;
            

        //    return View("Index");
        //}

        //private void GetAllPrinterList()
        //{
        //    ManagementScope objScope = new ManagementScope(ManagementPath.DefaultPath); //For the local Access
        //    objScope.Connect();
        //    List<string> lstPrinterList = new List<string>();
        //    SelectQuery selectQuery = new SelectQuery();
        //    selectQuery.QueryString = "Select * from win32_Printer";
        //    ManagementObjectSearcher MOS = new ManagementObjectSearcher(objScope, selectQuery);
        //    ManagementObjectCollection MOC = MOS.Get();
        //    foreach (ManagementObject mo in MOC)
        //    {
        //        lstPrinterList.Add(mo["Name"].ToString());
        //    }
        //}

        public void Print()
        {
           
            //from file
            //-------------
            //var document2 = new HtmlAgilityPack.HtmlDocument();
            //document2.Load(@"C:\Temp\Template.html");                             //(@"C:\Sourcecode\LabelPrintingVestey\LabelPrintingVestey\File\Template.html");
            //var nodes = document2.DocumentNode.SelectSingleNode("//table").InnerText;
            //-------------


            PrintDocument doc = new PrintDocument();
            doc.OriginAtMargins = false;

            doc.PrinterSettings.PrinterName = "Printronix Auto ID T8204 - PGL"; // System.Web.HttpUtility.UrlDecode("\\\\BFLHLWSVR0002.shl.lan\\Bidfresh Suite Henson MFP");  
            doc.PrintPage += (sender, ppeArgs) =>
            {
                int x = 10, y = 10;
                int width = 150, height = 40;

                System.Drawing.Font FontNormal = new System.Drawing.Font("Arial",12);
                Graphics g = ppeArgs.Graphics;
                Image i = Image.FromFile("C://Sourcecode//LabelPrintingVestey//LabelPrintingVestey//Images//OliverKayLogo1017.png");
                g.DrawImage(i, 185, 10, width, height);

                x += 0;
                y += height + 30;

                int hdy = (int)FontNormal.GetHeight(g) + 10; ;

                g.DrawString("Order No : 19717858", FontNormal, Brushes.Black, new PointF(x, y)); y += hdy;
                g.DrawString("Delivery Date: 30/09/2019", FontNormal, Brushes.Black, new PointF(x, y)); y += hdy;

                float width0 = 330.0F;
                float height0 = 30.0F;
                RectangleF drawRect0 = new RectangleF(x, y, width0, height0);
                int hdy0 = (int)drawRect0.Height + 10;
                // Draw rectangle to screen.
                Pen blackPen0 = new Pen(Color.Black);
                g.DrawRectangle(blackPen0, x, y, width0, height0);

                // Set format of string.
                StringFormat drawFormat0 = new StringFormat();
                drawFormat0.Alignment = StringAlignment.Near;

                g.DrawString("Route No.: 531       Drop No.: 92500", FontNormal, Brushes.Black, drawRect0, drawFormat0); y += hdy0;


                g.DrawString("Customer Reference No.: 71101752", FontNormal, Brushes.Black, new PointF(x, y)); y += hdy;
                g.DrawString("Customer Account Name:  T.JS DINER", FontNormal, Brushes.Black, new PointF(x, y)); y += hdy;
                // Create rectangle for drawing.
               
                float width1 = 330.0F;
                float height1 = 60.0F;
                RectangleF drawRect = new RectangleF(x, y, width1, height1);
                hdy = (int)drawRect.Height + 10;
                // Draw rectangle to screen.
                Pen blackPen = new Pen(Color.Black);
                g.DrawRectangle(blackPen, x, y, width1, height1);

                // Set format of string.
                StringFormat drawFormat = new StringFormat();
                drawFormat.Alignment = StringAlignment.Near;
                //e.Graphics.DrawString(drawString, drawFont, drawBrush, drawRect, drawFormat);
                g.DrawString("Address: HENDERSON RESTURANT GROUP LTD, 6 MAIN STREET TYNDRUM , FK20 8RY", FontNormal, Brushes.Black, drawRect, drawFormat); y += hdy;
                g.DrawString("Box: 1/1", FontNormal, Brushes.Black, new PointF(x, y)); y += hdy;
              

                //g.DrawString(nodes, FontNormal, Brushes.Black, new PointF(x, y)); y += hdy; // 0, 0, new StringFormat());
            };

            Margins margins = new Margins(10, 10, 10, 10);
            doc.DefaultPageSettings.Margins = margins;
            //doc.DefaultPageSettings.Landscape = true;
            
            //PrintDialog pdi = new PrintDialog();
            //pdi.Document = doc;
            PrintPreviewDialog printPrvDlg = new PrintPreviewDialog();
            printPrvDlg.Document = doc;
            printPrvDlg.ShowDialog();

           // if (pdi.ShowDialog() == DialogResult.OK)
           // {
                doc.Print();
           // }
        }

        public void PrintLanscape(DataSet ds, LabelModel mdl)
        {
            //from file
            //-------------
            //var document2 = new HtmlAgilityPack.HtmlDocument();
            //document2.Load(@"C:\Temp\Template.html");                             //(@"C:\Sourcecode\LabelPrintingVestey\LabelPrintingVestey\File\Template.html");
            //var nodes = document2.DocumentNode.SelectSingleNode("//table").InnerText;  mdl.Printer;
            //-------------
            if (ds.Tables[0].Rows.Count > 0) {
                for (int j = 1; j <= mdl.NoOfBoxes; j++) {

                    PrintDocument doc = new PrintDocument();
                    doc.OriginAtMargins = false;
                    doc.PrinterSettings.PrinterName = System.Web.HttpUtility.UrlDecode(mdl.Printer);  //System.Web.HttpUtility.UrlDecode("\\\\BFLHLWSVR0005\\SHARP_VEST");  //PrinterName;
                    doc.PrintPage += (sender, ppeArgs) =>
                    {
                        int x = 10, y = 10;
                        int width = 150, height = 40;

                        System.Drawing.Font FontNormal = new System.Drawing.Font("Arial", 12);
                        Graphics g = ppeArgs.Graphics;
                        Image i = Image.FromFile("C://Sourcecode//LabelPrintingVestey//LabelPrintingVestey//Images//OliverKayLogo1017.png");
                        //Image i = Image.FromFile("C://inetpub//wwwroot//OKPLabelPrint//Images//OliverKayLogo1017.png");
                        g.DrawImage(i, 285, 10, width, height);

                        x += 0;
                        y += height + 20;
                        int hdy = (int)FontNormal.GetHeight(g) + 10;
                       

                        //-------------------start writing string--------------------------------------//
                        System.Drawing.Font FontHeader = new System.Drawing.Font("Arial", 18);
                        int hdy00 = (int)FontHeader.GetHeight(g) + 10;
                        g.DrawString(ds.Tables[0].Rows[0]["CustomerAccountCode"] + " (" + ds.Tables[0].Rows[0]["OrderNo"] + ")           " + Convert.ToDateTime(ds.Tables[0].Rows[0]["CustomerDeliveryDate"]).ToShortDateString(), FontHeader, Brushes.Black, new PointF(x, y)); y += hdy00;
                        //g.DrawString("Delivery Date: " + ds.Tables[0].Rows[0]["CustomerDeliveryDate"], FontNormal, Brushes.Black, new PointF(x, y)); y += hdy;

                        float width0 = 430.0F;
                        float height0 = 30.0F;
                        RectangleF drawRect0 = new RectangleF(x, y, width0, height0);
                        int hdy0 = (int)drawRect0.Height + 10;
                        //Draw rectangle to screen.
                        Pen blackPen0 = new Pen(Color.Black);
                        g.DrawRectangle(blackPen0, x, y, width0, height0);

                        // Set format of string.
                        StringFormat drawFormat0 = new StringFormat();
                        drawFormat0.Alignment = StringAlignment.Near;

                        g.DrawString("Route No.: " + ds.Tables[0].Rows[0]["AdditionalInfo3"] , FontNormal, Brushes.Black, drawRect0, drawFormat0); y += hdy0;


                        g.DrawString("Reference No.: " +  ds.Tables[0].Rows[0]["OracleOrderNumber"] , FontNormal, Brushes.Black, new PointF(x, y)); y += hdy;
                        System.Drawing.Font FontNormal1 = new System.Drawing.Font("Arial", 12,FontStyle.Bold);
                        //FontNormal1.Bold(true);
                        int y12 = x + 100;
                        g.DrawString("Customer Account Name: " , FontNormal, Brushes.Black, new PointF(x, y));   //y += hdy;
                        g.DrawString("                                         " + ds.Tables[0].Rows[0]["CustomerAccountName"], FontNormal1, Brushes.Black, new PointF(x, y)); y += hdy;
                        // Create rectangle for drawing.

                        float width1 = 430.0F;
                        float height1 = 55.0F;

LabelPrintingAPP/LabelPrintingVestey/Views/Label/Index.cshtml
@{
    ViewBag.Title = "Order Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model LabelPrintingVestey.Models.LabelModel
<h2>Order Details</h2>
<style>
    .text-danger {
        font-color: #e60b0b;
    }

    .divDialog {
        border: 1px solid #8c8c8c;
        padding: 25px;
        box-shadow: 5px 10px 8px #888888;
        border-radius: 15px;
        border-spacing: 5px;
        display: none;
    }

    #lbldate {
        float: left
    }

    .close-image {
        display: block;
        float: right;
        position: relative;
        top: -10px;
        right: -10px;
        height: 20px;
    }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
   // $('#PrintLabelbtn').click(function (e) {
       // e.preventDefault();

        // TODO: Validate input
        function labelprint() {
          // var data = {
          
                // $( "#msgbox" ).text( "printing..." ).show();
                var orderno = $('#txtOrderNo').val();
                var noofbox = $('#txtNoOfBoxes').val();
                var printer = $('#selprinter').find(":selected").val();

                // alert(printer);
                //if ($('#selprinter').find(":selected").val() == "object:5") {
                //    printer = "\\\\BFLHLWSVR0005\\LBL_HEN"
                //} else if ($('#selprinter').find(":selected").val() == "object:4") {
                //    printer = "\\\\BFLHLWSVR0005\\LBL_BOL";}
                //else if ($('#selprinter').find(":selected").val() == "object:3") {
                //    printer = "\\\\BFLHLWSVR0005\\LBL_WED";

                //}
                //$('#selprinter').find(":selected").val();
                // };

            $.ajax({
                type: "POST",
                url: '@Url.Action("PrintLabel","Label")',
                content: "application/json; charset=utf-8",
                dataType: "json",
                data: {'orderno' : orderno, 'noofbox' : noofbox, 'printer' : printer },
                success: function (d) {
                    if (d.success == true) {
                        // window.location = "index.html";
                        //alert("printing");
                       // $("#msgbox").text("printing...").show().fadeOut(1000);
                    }
                    else { }
                },
                error: function (xhr, textStatus, errorThrown) {
                    // TODO: Show error
                } //ng-click="GetRecordByDeliveryDate()"  onclick="labelprint();"
            });
          
        }
   // });
</script>


<div ng-controller="AppLabelController">
    <form name="myForm" ng-submit="GetRecordByDeliveryDate(myForm.$valid)">
        <h3>
            <label id="lbldate">Search Order by Delivery Date :</label> <input type="submit" class="btn btn-toolbar" value="Search" style="float:right;" />
            <span style="overflow: hidden; padding-right: .5em;"><input class="form-control" id="dt" type="date" ng-change="changeformat()" ng-model="searchbyDeliveryDate" name="searchdate" required></span>
        </h3>
        <span class="error" ng-show="myForm.searchdate.$touched && myForm.searchdate.$invalid" style="float:right">*Delivery date is required.</span>
    </form>

 
        <div class="container">
            <hr style="margin-right:40px; width:100%" />
            <div class="row">
                <div class="col-25">
                    <label>Select Printer</label>
                </div>
                <div class="col-75">
                    @*<select ng-init="PrintModel.Printer = options[0]" ng-model="PrintModel.Printer"
                                ng-options="a.name for a in printer" id="selprinter" ng-model-options="">
                            <option value="">-- Select Printer --</option>
                        </select>*@

                    <select ng-model="PrintModel.Printer" id="selprinter" ng-init="PrintModel.Printer = options[0]" required name="selprinter">
                        <option value="">-- Select Printer --</option>
                        <option ng-repeat="item in printer" value="{{item.type}}">{{item.name}}</option>
                    </select>
                    @*<span class="error" ng-show="(myform1.selprinter.$dirty || submitted) && myform1.selprinter.$error.required">Please select printer</span>*@
                    @*<select ng-model="PrintModel.Printer" ng-options="item.type as item.name for item in printer"></select>*@
                </div>
            </div>
        </div>
        <br />



        <div class="container divDialog">

            <img class="close-image" src="~/Images/icons8-close-window-26.png" ng-click="hidePrintDailog()" />
            <div class="row">
                <div class="col-25">
                    <label for="fname">Order No.(or Oracle Order No.):</label>
                </div>
                <div class="col-75">
                    <input class="textbox" type="text" ng-model="PrintModel.OrderNo" id="txtOrderNo" required name="txtOrderno" />
                    @*<span class="error" ng-show="(myform1.txtOrderno.$dirty || submitted) && myform1.txtOrderno.$error.required">Order no. is Required</span>*@
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="lname">No.Of Boxes:</label>
                </div>
                <div class="col-75">
                    <input class="textbox" type="text" ng-model="PrintModel.NoOfBoxes" id="txtNoOfBoxes" required name="txtnoboxes" />
                    @*<span class="error" ng-show="(myform1.txtnoboxes.$dirty || submitted) && myform1.txtnoboxes.$error.required">No.Of boxes is Required</span>*@
                </div>
            </div>

            <div class="row">
                <div class="col-25">
                </div>
                <div class="col-75" style="float:right;">
                    <input type="submit" class="btn btn-toolbar" value="Print Label" id="PrintLabelbtn" onclick="labelprint();"/>
                    <span id="msgbox"></span>
                </div>
            </div>
        </div>
   

    <h2 style="text-align:center">List of All Orders</h2>
    <br>
    <hr />
    <div>
        <p><input type="text" ng-model="Anytext" placeholder="Free text search"></p>
    </div>
    <div>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Oracle OrderNo.</th>
                <th>Depot</th>
                <th>Customer Code</th>
                <th>Account Name</th>
                <th>Account Location</th>
                <th>OrderNo.</th>

                <th>Delivery Date</th>
            </tr>
            <tr ng-repeat="ord in Orders | filter : Anytext">

                <td>{{ord.ID}}</td>
                <td>{{ord.OracleOrderNo}}</td>
                <td>{{ord.CustomerSite}}</td>
                <td>{{ord.CustomerAccountCode}}</td>
                <td>{{ord.CustomerAccountName}}</td>
                <td>{{ord.CustomerAccountLocation}}</td>
                <td>{{ord.OrderNo}}</td>

                <td>{{ord.CustomerDeliveryDate}}</td>
                <td>
                    <input type="button" class="btn btn-toolbar" value="Print" ng-click="ShowPrintDialog(ord)" />
                   
                </td>
            </tr>
        </table>
    </div>
</div>